spring:
  application:
    name: crm-helpdesk
  profiles:
    active: dev
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    com.serviclient: DEBUG
    org.springframework.security: INFO
